name: 잡무(Chore)
description: src나 tests 파일을 바꾸지 않는 일들
title: "[Chore] "
labels: ["chore"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Descriptions
    description: Clearly describe what change is needed and why. If this changes code then please use another issue type.
  validations:
    required: true
- type: textarea
  attributes:
    label: Requirements
    description: "- [ ] No functional changes to the code"
  validations:
    required: false
