name: 잡무(Chore)
description: `src`나 `test`파일을 바꾸지 않는 일들
title: "[Chore] "
labels: ["chore"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Descriptions
    description: Clearly describe what change is needed and why. If this changes code then please use another issue type.
    무엇을, 왜 변경했는지 설명해주세요. 만약 code를 바꾸는 경우에는 반드시 다른 issue 타입을 사용해주세요
  validations:
    required: true
- type: textarea
  attributes:
    label: Requirements
    description: - [ ] No functional changes to the code
                 - [ ] 코드의 기능적 변경이 없음
  validations:
    required: false
